### PR TITLE
Update ETFlex levels 1 and 2 after heat project

### PR DESCRIPTION
**Pull request by marliekeverweij**
In this PR I:
- renamed space_heater and water_heater nodes
- updated insulation level slider (now it only sets terraced houses, first it only did old houses)
- changed micro chp slider to electric trucks

I wanted to update the scenario behind ETFlex, but I didn't know how. I wanted to only built terraced houses, so the insulation slider would have more influence (since the insulation slider can only set one input statement: `households_insulation_level_terraced_houses`). Do you know how to do this @ChaelKruip ? I does work now though, but it could work better. So has no priority I think :) 

Joris and I were wondering if merit is switched on or off in ETFlex. When opening the scenario in ETModel we saw that it is switched on. The conclusion of this issue https://github.com/quintel/etflex/issues/421 is to switch it off. I actually think that that's not possible, since merit is automatically switched on in a new scenario.

Notifying @jorisberkhout 

Screen Shot 2019-03-15 at 17 08 28

### CODE REVIEW

**Comment by ChaelKruip** [comment]
> I wanted to update the scenario behind ETFlex, but I didn't know how. I wanted to only built terraced houses, so the insulation slider would have more influence (since the insulation slider can only set one input statement: households_insulation_level_terraced_houses). Do you know how to do this @ChaelKruip ? I does work now though, but it could work better. So has no priority I think :)

@redekok can you investigate?

**Comment by ChaelKruip** [comment]
>  I actually think that that's not possible, since merit is automatically switched on in a new scenario.

@antw do you know this? I think it should possible to turn Merit off for ETFlex scenario's and it would likely make the game more interesting (no automatic balancing of demand and supply of electricity).

**Comment by antw** [comment]
> @antw do you know this? I think it should possible to turn Merit off for ETFlex scenario's and it would likely make the game more interesting 

I've sent a commit to the `fix-etflex` branch which will turn off the merit order for new scenarios created in the "Balance energy demand and supply" section of ETFlex. The "Create your house of the future" section will still have the merit order enabled, but it too can have it turned off if need be.

**Comment by redekok** [comment]
@antw I've updated the [Dutch](https://github.com/quintel/etflex/blob/6f93f19e69fcde71c0611cb4a428b1db79e9ff37/config/locales/inputs.nl.yml) and [English](https://github.com/quintel/etflex/blob/6f93f19e69fcde71c0611cb4a428b1db79e9ff37/config/locales/inputs.en.yml) translation files for ETFlex. However, it doesn't seem to update the translations in the front-end. I also noticed that the [translations.js](https://github.com/quintel/etflex/blob/fix-etflex/app/assets/javascripts/i18n/translations.js) file isn't updated. Should we run any script to update the translations?

**Comment by antw** [comment]
> Should we run any script to update the translations?

ETFlex is a little old and doesn't update the translations automatically.

You need to run `bundle exec rake i18n:js:export`

**Comment by redekok** [comment]
In addition to @marliekeverweij's efforts for updating level 1, the following (suggested) changes are implemented:
- The merit order is disabled for level 1.
- There are only terraced houses, no other housing types. Therefore, the only insulation level set is the one for terraced houses. The cost deviation query is also updated for this change.

Furthermore, level 2 is updated:
- The Micro CHP is replaced by district heating.

For both level 1 and 2, the translations are updated.

Notifying @marliekeverweij, @ChaelKruip

**Comment by redekok** [comment]
@antw Would it be possible to clear the high scores for levels 1 and 2? Due to the changes by this PR, the user presumably won't be able to achieve the same high scores as before.

**Comment by antw** [comment]
> Would it be possible to clear the high scores for levels 1 and 2?

Yes I suppose so. Perhaps it would be preferable to adjust the old scores down – to be closer to the new scores – rather than removing them entirely?

**Comment by redekok** [comment]
> Yes I suppose so. Perhaps it would be preferable to adjust the old scores down – to be closer to the new scores – rather than removing them entirely?

Yes, maybe that's preferred over removing them entirely, indeed. @marliekeverweij @ChaelKruip What are your thoughts on this?

**Comment by ChaelKruip** [comment]
> Yes, maybe that's preferred over removing them entirely, indeed. @marliekeverweij @ChaelKruip What are your thoughts on this?

If that is easily done I'm all for it!

**Comment by antw** [comment]
> If that is easily done I'm all for it!

It is indeed very easy: a single database query will adjust all the old scores. All we would need to do is decide by how much to reduce the scores.

That said, the leaderboard only shows scores from the past week, so older scores are not hugely relevant. There are already a good number of recent scores in the 700-800 range so I'm not sure it's necessary for us to change the old scores anymore.

**Comment by redekok** [comment]
> I'm not sure it's necessary for us to change the old scores anymore.

I agree. However, if time permits, it would be worthwhile to look into the scores method another time since it currently doesn't seem too challenging to get a high score:

image

**Comment by ChaelKruip** [comment]
> I agree. However, if time permits, it would be worthwhile to look into the scores method another time since it currently doesn't seem too challenging to get a high score:

This has always been the case but we might think about a way to make this more difficult again (re-enable the Merit Order might make things less predictable 😆). @redekok we can have a go at this without help from @antw.

**Pull request merged**
